#!/usr/bin/env bash
if [ "$#" -eq 0 ] || [[ " $@ " =~ " --help " ]]; then

YELLOW='\033[1;33m'
NC='\033[0m'
echo -e "${YELLOW}
█▀ █▀▀ █▀▀ █▀█ █▀▀ ▀█▀ █▀   █▀▀ █   █
▄█ ██▄ █▄▄ █▀▄ ██▄  █  ▄█   █▄▄ █▄▄ █
${NC}"

fi

version_command() {
  echo "$version"
}

secrets_usage() {
  printf "secrets - Manage secrets as encrypted yaml files.\n\n"

  printf "%s\n" "Usage:"
  printf "  secrets COMMAND\n"
  printf "  secrets [COMMAND] --help | -h\n"
  printf "  secrets --version | -v\n"
  echo

  printf "%s\n" "Commands:"
  printf "  %s   List secrets.\n" "ls  "
  printf "  %s   Remove secrets.\n" "rm  "
  printf "  %s   Create secret.\n" "new "
  printf "  %s   Output secret.\n" "get "
  printf "  %s   Edit secret.\n" "edit"
  echo

  if [[ -n "$long_usage" ]]; then
    printf "%s\n" "Options:"

    printf "  %s\n" "--help, -h"
    printf "    Show this help\n"
    echo
    printf "  %s\n" "--version, -v"
    printf "    Show version number\n"
    echo

  fi
}

secrets_ls_usage() {
  printf "secrets ls - List secrets.\n\n"

  printf "%s\n" "Usage:"
  printf "  secrets ls [OPTIONS]\n"
  printf "  secrets ls --help | -h\n"
  echo

  if [[ -n "$long_usage" ]]; then
    printf "%s\n" "Options:"

    printf "  %s\n" "--yaml"
    printf "    List secrets in as yaml instead of plain text.\n"
    echo

    printf "  %s\n" "--passphrase"
    printf "    Passphrase to use for decryption.\n"
    echo

    printf "  %s\n" "--help, -h"
    printf "    Show this help\n"
    echo

  fi
}

secrets_rm_usage() {
  printf "secrets rm - Remove secrets.\n\n"

  printf "%s\n" "Usage:"
  printf "  secrets rm NAME... [OPTIONS]\n"
  printf "  secrets rm --help | -h\n"
  echo

  if [[ -n "$long_usage" ]]; then
    printf "%s\n" "Options:"

    printf "  %s\n" "--force"
    printf "    Remove the secret(s) without confirmation.\n"
    echo

    printf "  %s\n" "--help, -h"
    printf "    Show this help\n"
    echo

    printf "%s\n" "Arguments:"

    printf "  %s\n" "NAME..."
    printf "    The name of the secret(s).\n"
    echo

  fi
}

secrets_new_usage() {
  printf "secrets new - Create secret.\n\n"

  printf "%s\n" "Usage:"
  printf "  secrets new NAME [OPTIONS] [--] [ARBITRARY OPTIONS TO USE AS KEY/VALUE DATA FOR YOUR SECRET FILE....]\n"
  printf "  secrets new --help | -h\n"
  echo

  if [[ -n "$long_usage" ]]; then
    printf "%s\n" "Options:"

    printf "  %s\n" "--preview"
    printf "    Preview the generated yaml file without saving it.\n"
    echo

    printf "  %s\n" "--from-yaml FILE-OR-STRING"
    printf "    Use existing yaml or yaml file to create secret.\n"
    echo

    printf "  %s\n" "--namespace NAMESPACE"
    printf "    The namespace to store secret in.\n"
    echo

    printf "  %s\n" "--passphrase PASSPHRASE"
    printf "    Passphrase to use for encryption.\n"
    echo

    printf "  %s\n" "--help, -h"
    printf "    Show this help\n"
    echo

    printf "%s\n" "Arguments:"

    printf "  %s\n" "NAME"
    printf "    The name of the secret.\n"
    echo

  fi
}

secrets_get_usage() {
  printf "secrets get - Output secret.\n\n"

  printf "%s\n" "Usage:"
  printf "  secrets get NAME [OPTIONS]\n"
  printf "  secrets get --help | -h\n"
  echo

  if [[ -n "$long_usage" ]]; then
    printf "%s\n" "Options:"

    printf "  %s\n" "--key YAML-KEY"
    printf "    Get the value for a specific key in the secret.\n"
    echo

    printf "  %s\n" "--namespace NAMESPACE"
    printf "    The namespace the secret is stored in.\n"
    echo

    printf "  %s\n" "--passphrase PASSPHRASE"
    printf "    Passphrase to use for decryption.\n"
    echo

    printf "  %s\n" "--help, -h"
    printf "    Show this help\n"
    echo

    printf "%s\n" "Arguments:"

    printf "  %s\n" "NAME"
    printf "    The name of the secret to output.\n"
    echo

  fi
}

secrets_edit_usage() {
  printf "secrets edit - Edit secret.\n\n"

  printf "%s\n" "Usage:"
  printf "  secrets edit NAME [OPTIONS] [--] [ARBITRARY OPTIONS TO USE AS KEY/VALUE DATA FOR YOUR SECRET FILE....]\n"
  printf "  secrets edit --help | -h\n"
  echo

  if [[ -n "$long_usage" ]]; then
    printf "%s\n" "Options:"

    printf "  %s\n" "--preview"
    printf "    Preview the generated yaml file without saving it.\n"
    echo

    printf "  %s\n" "--from-yaml FILE-OR-STRING"
    printf "    Use existing yaml or yaml file to create secret.\n"
    echo

    printf "  %s\n" "--namespace NAMESPACE"
    printf "    The namespace to store secret in.\n"
    echo

    printf "  %s\n" "--passphrase PASSPHRASE"
    printf "    Passphrase to use for encryption.\n"
    echo

    printf "  %s\n" "--help, -h"
    printf "    Show this help\n"
    echo

    printf "%s\n" "Arguments:"

    printf "  %s\n" "NAME"
    printf "    The name of the secret.\n"
    echo

  fi
}

normalize_input() {
  local arg passthru
  passthru=false

  while [[ $# -gt 0 ]]; do
    arg="$1"
    if [[ $passthru == true ]]; then
      input+=("$arg")
    elif [[ $arg =~ ^(--[a-zA-Z0-9_\-]+)=(.+)$ ]]; then
      input+=("${BASH_REMATCH[1]}")
      input+=("${BASH_REMATCH[2]}")
    elif [[ $arg =~ ^(-[a-zA-Z0-9])=(.+)$ ]]; then
      input+=("${BASH_REMATCH[1]}")
      input+=("${BASH_REMATCH[2]}")
    elif [[ "$arg" == "--" ]]; then
      passthru=true
      input+=("$arg")
    else
      input+=("$arg")
    fi

    shift
  done
}

print_in_color() {
  local color="$1"
  shift
  if [[ -z ${NO_COLOR+x} ]]; then
    printf "$color%b\e[0m\n" "$*";
  else
    printf "%b\n" "$*";
  fi
}

red() { print_in_color "\e[31m" "$*"; }
green() { print_in_color "\e[32m" "$*"; }
yellow() { print_in_color "\e[33m" "$*"; }
blue() { print_in_color "\e[34m" "$*"; }
magenta() { print_in_color "\e[35m" "$*"; }
cyan() { print_in_color "\e[36m" "$*"; }
bold() { print_in_color "\e[1m" "$*"; }
underlined() { print_in_color "\e[4m" "$*"; }
red_bold() { print_in_color "\e[1;31m" "$*"; }
green_bold() { print_in_color "\e[1;32m" "$*"; }
yellow_bold() { print_in_color "\e[1;33m" "$*"; }
blue_bold() { print_in_color "\e[1;34m" "$*"; }
magenta_bold() { print_in_color "\e[1;35m" "$*"; }
cyan_bold() { print_in_color "\e[1;36m" "$*"; }
red_underlined() { print_in_color "\e[4;31m" "$*"; }
green_underlined() { print_in_color "\e[4;32m" "$*"; }
yellow_underlined() { print_in_color "\e[4;33m" "$*"; }
blue_underlined() { print_in_color "\e[4;34m" "$*"; }
magenta_underlined() { print_in_color "\e[4;35m" "$*"; }
cyan_underlined() { print_in_color "\e[4;36m" "$*"; }

error(){
    exit_code="${2:-}"
    echo "$(red_bold [ERROR]): $1"
    if [ ! -z "$exit_code" ]; then
        exit $exit_code
    fi
}

warning(){
    exit_code="${2:-}"
    echo "$(yellow_bold [WARNING]): $1"
    if [ ! -z "$exit_code" ]; then
        exit $exit_code
    fi
}
success(){
    echo "$(green_bold [SUCCESS]): $1"
}
info(){
    echo "$(cyan_bold [INFO]): $1"
}

filter_ensure_default_files() {
    context="$(get_cli_context)"
    mkdir -p $(secrets_context_path "secrets/")
}

remove_trailing() {
    value="$1"
    char="$2"
    echo ${value%"$char"}
}
make_sha() {
    value="$1"
    echo -n "$value" | sha1sum | cut -d ' ' -f1
}
confirm() {
    echo -n "$(yellow_bold [CONFIRM]): $1 [y/n]: "
    read -r -p "" response
    [[ "$response" == [Yy] ]]
}

get_decrypted_secret_data() {
    secret_path="$1"
    passphrase="$2"
    yaml_data=$(cat "$secret_path" | openssl enc -aes-256-cbc -pbkdf2 -salt -pass pass:$passphrase -d -base64)
    echo "$yaml_data"
}

get_namespace_from_env_vars() {
    context="$(get_cli_context)"
    context=$(echo $context | tr '[:lower:]' '[:upper:]')
    context_var="SECRETS_CLI_${context}_NAMESPACE"
    namespace="${!context_var}"

    if [ -z "$namespace" ]; then
        namespace="${SECRETS_CLI_NAMESPACE:-}"
    fi
    echo $namespace
}

get_passphrase_from_env_vars() {
    context="$(get_cli_context)"
    context=$(echo $context | tr '[:lower:]' '[:upper:]')
    context_var="SECRETS_CLI_${context}_PASSPHRASE"
    passphrase="${!context_var}"

    if [ -z "$passphrase" ]; then
        passphrase="${SECRETS_CLI_PASSPHRASE:-}"
    fi

    echo $passphrase

}

parse_value_for_yq_assignment() {
    value="$1"
    if [[ "$value" =~ ^[0-9]+$ ]] || [[ "$value" == "true" ]] || [[ "$value" == "false" ]] || [[ "$value" == "null" ]];
    then
        echo "$value"
    else
        echo "\"$value\""
    fi
}

generate_yaml_from_other_args(){
    i=0
    yaml=""
    declare -n args=$1
    declare -A keys_seen  # Track repeated keys
    while [ $i -lt ${#args[@]} ]; do
        raw_key="${args[i]}"
        key="${args[i]#--}"  # Remove leading "--"
        value="${args[i+1]}" # Get the corresponding value

        i=$((i + 2))         # Move to the next pair
        # If value is empty or another flag, treat it as a boolean "true"
        if [[ -z "$value" || "$value" =~ ^--[^-] ]]; then
            value="true"
            ((i--))  # Step back since value is actually a new key
        fi
        # Check if key already exists in YAML
        if [[ -n "${keys_seen[$key]}" ]]; then
            # Convert existing key to an array if not already one
            if [[ $(echo "$yaml" | yq ".${key} | type") != "!!seq" ]];
            then
                current_value=$(echo "$yaml" | yq -r ".${key}")
                current_value=$(parse_value_for_yq_assignment "$current_value")
                yaml=$(echo "$yaml" | yq ".${key} = [$current_value]")
            fi
            value=$(parse_value_for_yq_assignment "$value")
            yaml=$(echo "$yaml" | yq ".${key} += [$value]")
        elif [[ "$raw_key" =~ ^--[^-] ]];
        then
            value=$(parse_value_for_yq_assignment "$value")
            yaml=$(echo "$yaml" | yq ".${key} = $value")
            keys_seen["$key"]=1  # Mark key as seen
        fi
    done
    echo "$yaml"
}

get_cli_context() {
    context="${SECRETS_CLI_CONTEXT:-default}"
    echo $context
}

secrets_context_path() {
    path="${1:-/}"
    context="$(get_cli_context)"
    base="$HOME/.secrets/contexts/$context"
    path="$base/$path"
    echo $(remove_trailing "$path" "/")
}

tmp_path() {
    path="${1:-/}"
    base="/tmp/.secrets"
    path="$base/$path"
    echo $(remove_trailing "$path" "/")
}

secrets_path() {
    path="${1:-/}"
    base="$HOME/.secrets"
    path="$base/$path"
    echo $(remove_trailing "$path" "/")
}

secrets_cli_path() {
    path="${1:-/}"
    base="$SECRETS_CLI_PATH"
    path="$base/$path"
    echo $(remove_trailing "$path" "/")
}

secrets_ls_command() {

  secret_names=("Name")
  path=$(secrets_context_path "secrets")
  files=$(find $path -type f)

  if [ -z "$files" ]; then
      warning "No secrets found." 0
  fi

  passphrase=$(get_passphrase_from_env_vars ${args[--passphrase]})
  if [ -z "$passphrase" ];
  then
      passphrase="${args[--passphrase]}"
  fi
  if [ -z "$passphrase" ]; then
      info "Enter passphrase for encryption: "
      read -s passphrase
      info "Confirm passphrase: "
      read -s confirm_passphrase
      if [ "$passphrase" != "$confirm_passphrase" ]; then
          error "Passphrases do not match." 1
      fi
  fi

  yaml=""
  namespaces=()
  base=$(secrets_context_path "secrets")
  for file in $(find $base -maxdepth 1 -mindepth 1 -type d); do
      # get last part of path
      namespace=$(basename $file)
      namespaces+=($namespace)
      yaml="$(echo "$yaml" | yq ".\"$namespace\" = []")"
  done
  as_yaml=${args[--yaml]:-0}
  for namespace in ${namespaces[@]}; do
      if [  $as_yaml != 1 ]; then
         echo "$namespace namespace secrets:"
      fi
      for file in $(find $path/$namespace -type f); do
          secret=$(cat $file | openssl enc -d -a -aes-256-cbc -pbkdf2 -salt -pass pass:$passphrase)
          name=$(echo "$secret" | yq -r ".__secret_cli_name__")
          yaml=$(echo "$yaml" | yq ".$namespace += \"$name\"")
          if [  $as_yaml != 1 ]; then
              echo "  * $name"
          fi
      done
      if [  $as_yaml != 1 ]; then
          echo ""
      fi
  done

  if [  $as_yaml != 1 ]; then
      exit 0
  fi

  echo "$yaml" | yq

}

secrets_rm_command() {

  names_string=""
  secret_names=()

  for opt in ${!args[@]}; do
      name="${args[$opt]}"
      if [[ ! "$opt" =~ ^-- ]]; then
          secret_names+=("$name")
      fi
  done

  for secret_name in ${secret_names[@]}; do
      secret_sha=$(make_sha "$secret_name")
      secret_path=$(secrets_context_path "secrets/$secret_sha")
      [[ -n "$names_string" ]] && names_string+=", "
      names_string+="$secret_name"

      if [ ! -f "$secret_path" ]; then
          error "Secret with name '$secret_name' doesnt exist." 1
      fi
  done

  if [[ ${args[--force]} != 1 ]] && ! confirm "Are you sure you want to remove '$names_string' from your stored secrets?"; then
      warning "Aborted." 1
  fi

  for secret_name in ${args[@]}; do
      secret_sha=$(make_sha "$secret_name")
      secret_path=$(secrets_context_path "secrets/$secret_sha")
      rm -f "$secret_path"
      if [ $? -eq 0 ]; then
          success "Secret '$secret_name' removed successfully."
      else
          error "Failed to remove secret '$secret_name'."
      fi
  done

}

secrets_new_command() {

  secret_name="${args[name]}"
  secret_sha=$(make_sha "$secret_name")
  namespace=$(get_namespace_from_env_vars)
  if [ ! -z "${args[--namespace]}" ];
  then
      namespace="${args[--namespace]}"
  fi

  if [ -z "$namespace" ]; then
      namespace="default"
  fi

  secret_path=$(secrets_context_path "secrets/$namespace/$secret_sha")

  if [ -f "$secret_path" ]; then
      error "Secret with name '$secret_name' already exists in namespace '$namespace'." 1
  fi

  yaml_data=$(generate_yaml_from_other_args other_args)
  if [ ! -z "${args[--from-yaml]}" ]; then
      if [ -f "${args[--from-yaml]}" ]; then
          file_data=$(cat "${args[--from-yaml]}")
      else
          file_data="${args[--from-yaml]}"
      fi
      # merge yaml from options if given
      mkdir -p "$(tmp_path)"
      echo "$yaml_data" > "$(tmp_path 1.yaml)"
      echo "$file_data" > "$(tmp_path 2.yaml)"
      yaml_data="$(yq eval-all '. as $item ireduce ({}; . * $item )' "$(tmp_path 1.yaml)" "$(tmp_path 2.yaml)")"
      rm -rf "$(tmp_path)"
  fi

  preview=${args[--preview]:-0}
  if [  $preview = 1 ]; then
     echo "$yaml_data" | yq
     exit 0
  fi

  if [ -z "$yaml_data" ]; then
      error "No data provided for secret." 1
  fi

  yaml_data=$(echo "$yaml_data" | yq eval '. + {"__secret_cli_name__": "'$secret_name'"}')
  passphrase=$(get_passphrase_from_env_vars)

  if [ ! -z "${args[--passphrase]}" ];
  then
      passphrase="${args[--passphrase]}"
  fi

  if [ -z "$passphrase" ]; then
      info "Enter passphrase for encryption: "
      read -s passphrase
      info "Confirm passphrase: "
      read -s confirm_passphrase
      if [ "$passphrase" != "$confirm_passphrase" ]; then
          error "Passphrases do not match." 1
      fi
  fi

  secret=$(echo "$yaml_data" |  openssl enc -aes-256-cbc -pbkdf2 -salt -pass pass:$passphrase -base64)

  mkdir -p "$(dirname "$secret_path")"
  echo "$secret" > "$secret_path"

  success "Created new secret with name '$secret_name' in namespace '$namespace'."

}

secrets_get_command() {

  secret_name="${args[name]}"
  secret_sha=$(make_sha "$secret_name")
  namespace=$(get_namespace_from_env_vars)
  if [ ! -z "${args[--namespace]}" ];
  then
      namespace="${args[--namespace]}"
  fi

  if [ -z "$namespace" ]; then
      namespace="default"
  fi

  secret_path=$(secrets_context_path "secrets/$namespace/$secret_sha")

  if [ ! -f "$secret_path" ]; then
      error "Secret with name '$secret_name' does not exists in namespace '$namespace'." 1
  fi

  passphrase=$(get_passphrase_from_env_vars)

  if [ ! -z "${args[--passphrase]}" ];
  then
      passphrase="${args[--passphrase]}"
  fi

  if [ -z "$passphrase" ]; then
      info "Enter passphrase for encryption: "
      read -s passphrase
      info "Confirm passphrase: "
      read -s confirm_passphrase
      if [ "$passphrase" != "$confirm_passphrase" ]; then
          error "Passphrases do not match." 1
      fi
  fi

  yaml_data=$(get_decrypted_secret_data "$secret_path" "$passphrase")
  yaml_data="$(echo "$yaml_data" | yq 'del(.["__secret_cli_name__"])')"

  if [ -z "${args[--key]}" ];
  then
      echo "$yaml_data" | yq
      exit 0
  fi

  key="${args[--key]}"

  value=$(echo "$yaml_data" | yq -r ".$key")

  echo "$value"

}

secrets_edit_command() {

  secret_name="${args[name]}"
  secret_sha=$(make_sha "$secret_name")
  namespace=$(get_namespace_from_env_vars)
  if [ ! -z "${args[--namespace]}" ];
  then
      namespace="${args[--namespace]}"
  fi

  if [ -z "$namespace" ]; then
      namespace="default"
  fi

  secret_path=$(secrets_context_path "secrets/$namespace/$secret_sha")

  if [ ! -f "$secret_path" ]; then
      error "Secret with name '$secret_name' does not exist in namespace '$namespace'." 1
  fi

  yaml_data=$(generate_yaml_from_other_args other_args)
  if [ ! -z "${args[--from-yaml]}" ]; then
      if [ -f "${args[--from-yaml]}" ]; then
          file_data=$(cat "${args[--from-yaml]}")
      else
          file_data="${args[--from-yaml]}"
      fi
      # merge yaml from options if given
      mkdir -p "$(tmp_path)"
      echo "$yaml_data" > "$(tmp_path 1.yaml)"
      echo "$file_data" > "$(tmp_path 2.yaml)"
      yaml_data="$(yq eval-all '. as $item ireduce ({}; . * $item )' "$(tmp_path 1.yaml)" "$(tmp_path 2.yaml)")"
      rm -rf "$(tmp_path)"
  fi

  if [ -z "$yaml_data" ]; then
      error "No update data provided for secret." 1
  fi

  passphrase=$(get_passphrase_from_env_vars)

  if [ ! -z "${args[--passphrase]}" ];
  then
      passphrase="${args[--passphrase]}"
  fi

  secret_yaml_data=$(get_decrypted_secret_data "$secret_path" "$passphrase")
  mkdir -p "$(tmp_path)"
  echo "$secret_yaml_data" > "$(tmp_path 1.yaml)"
  echo "$yaml_data" > "$(tmp_path 2.yaml)"
  yaml_data="$(yq eval-all '. as $item ireduce ({}; . * $item )' "$(tmp_path 1.yaml)" "$(tmp_path 2.yaml)")"
  yaml_data="$(echo "$yaml_data" | yq 'del(.["__secret_cli_name__"])')"

  rm -rf "$(tmp_path)"

  preview=${args[--preview]:-0}
  if [  $preview = 1 ]; then
      echo "$yaml_data" | yq
      exit 0
  fi

  if [ -z "$passphrase" ]; then
      info "Enter passphrase for encryption: "
      read -s passphrase
      info "Confirm passphrase: "
      read -s confirm_passphrase
      if [ "$passphrase" != "$confirm_passphrase" ]; then
          error "Passphrases do not match." 1
      fi
  fi

  yaml_data=$(echo "$yaml_data" | yq eval '. + {"__secret_cli_name__": "'$secret_name'"}')
  secret=$(echo "$yaml_data" |  openssl enc -aes-256-cbc -pbkdf2 -salt -pass pass:$passphrase -base64)

  mkdir -p "$(dirname "$secret_path")"
  # echo "$secret" > "$secret_path"

  success "Updated secret with name '$secret_name' in namespace '$namespace'."

}

parse_requirements() {

  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --version | -v)
        version_command
        exit
        ;;

      --help | -h)
        long_usage=yes
        secrets_usage
        exit
        ;;

      *)
        break
        ;;

    esac
  done

  action=${1:-}

  case $action in
    -*) ;;

    ls)
      action="ls"
      shift
      secrets_ls_parse_requirements "$@"
      shift $#
      ;;

    rm)
      action="rm"
      shift
      secrets_rm_parse_requirements "$@"
      shift $#
      ;;

    new)
      action="new"
      shift
      secrets_new_parse_requirements "$@"
      shift $#
      ;;

    get)
      action="get"
      shift
      secrets_get_parse_requirements "$@"
      shift $#
      ;;

    edit)
      action="edit"
      shift
      secrets_edit_parse_requirements "$@"
      shift $#
      ;;

    "")
      secrets_usage >&2
      exit 1
      ;;

    *)
      printf "invalid command: %s\n" "$action" >&2
      exit 1
      ;;

  esac

  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in

      -?*)
        printf "invalid option: %s\n" "$key" >&2
        exit 1
        ;;

      *)

        printf "invalid argument: %s\n" "$key" >&2
        exit 1

        ;;

    esac
  done

}

secrets_ls_parse_requirements() {

  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --help | -h)
        long_usage=yes
        secrets_ls_usage
        exit
        ;;

      *)
        break
        ;;

    esac
  done

  missing_deps=

  if ! command -v yq >/dev/null 2>&1; then
    printf "missing dependency: yq\n" >&2
    missing_deps=1
  else
    deps['yq']="$(command -v yq | head -n1)"
  fi

  if ! command -v sha1sum >/dev/null 2>&1; then
    printf "missing dependency: sha1sum\n" >&2
    missing_deps=1
  else
    deps['sha1sum']="$(command -v sha1sum | head -n1)"
  fi

  if [[ -n $missing_deps ]]; then
    exit 1
  fi

  action="ls"

  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in

      --yaml)

        args['--yaml']=1
        shift
        ;;

      --passphrase)

        args['--passphrase']=1
        shift
        ;;

      -?*)
        printf "invalid option: %s\n" "$key" >&2
        exit 1
        ;;

      *)

        printf "invalid argument: %s\n" "$key" >&2
        exit 1

        ;;

    esac
  done

  filter_error=$(filter_ensure_default_files)
  if [[ -n $filter_error ]]; then
    echo "$filter_error" >&2
    exit 1
  fi

}

secrets_rm_parse_requirements() {

  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --help | -h)
        long_usage=yes
        secrets_rm_usage
        exit
        ;;

      *)
        break
        ;;

    esac
  done

  missing_deps=

  if ! command -v yq >/dev/null 2>&1; then
    printf "missing dependency: yq\n" >&2
    missing_deps=1
  else
    deps['yq']="$(command -v yq | head -n1)"
  fi

  if ! command -v sha1sum >/dev/null 2>&1; then
    printf "missing dependency: sha1sum\n" >&2
    missing_deps=1
  else
    deps['sha1sum']="$(command -v sha1sum | head -n1)"
  fi

  if [[ -n $missing_deps ]]; then
    exit 1
  fi

  action="rm"

  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in

      --force)

        args['--force']=1
        shift
        ;;

      -?*)
        printf "invalid option: %s\n" "$key" >&2
        exit 1
        ;;

      *)

        escaped="$(printf '%q' "$1")"
        if [[ -z ${args['name']+x} ]]; then
          args['name']="$escaped"
        else
          args['name']="${args['name']} $escaped"

        fi
        shift

        ;;

    esac
  done

  if [[ -z ${args['name']+x} ]]; then
    printf "missing required argument: NAME\nusage: secrets rm NAME... [OPTIONS]\n" >&2

    exit 1
  fi

}

secrets_new_parse_requirements() {

  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --help | -h)
        long_usage=yes
        secrets_new_usage
        exit
        ;;

      *)
        break
        ;;

    esac
  done

  missing_deps=

  if ! command -v yq >/dev/null 2>&1; then
    printf "missing dependency: yq\n" >&2
    missing_deps=1
  else
    deps['yq']="$(command -v yq | head -n1)"
  fi

  if ! command -v sha1sum >/dev/null 2>&1; then
    printf "missing dependency: sha1sum\n" >&2
    missing_deps=1
  else
    deps['sha1sum']="$(command -v sha1sum | head -n1)"
  fi

  if [[ -n $missing_deps ]]; then
    exit 1
  fi

  action="new"

  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in

      --preview)

        args['--preview']=1
        shift
        ;;

      --from-yaml)

        if [[ -n ${2+x} ]]; then
          args['--from-yaml']="$2"
          shift
          shift
        else
          printf "%s\n" "--from-yaml requires an argument: --from-yaml FILE-OR-STRING" >&2
          exit 1
        fi
        ;;

      --namespace)

        if [[ -n ${2+x} ]]; then
          args['--namespace']="$2"
          shift
          shift
        else
          printf "%s\n" "--namespace requires an argument: --namespace NAMESPACE" >&2
          exit 1
        fi
        ;;

      --passphrase)

        if [[ -n ${2+x} ]]; then
          args['--passphrase']="$2"
          shift
          shift
        else
          printf "%s\n" "--passphrase requires an argument: --passphrase PASSPHRASE" >&2
          exit 1
        fi
        ;;

      --)
        shift
        other_args+=("$@")
        break
        ;;

      -?*)
        other_args+=("$1")
        shift
        ;;

      *)

        if [[ -z ${args['name']+x} ]]; then
          args['name']=$1
          shift
        else
          other_args+=("$1")
          shift
        fi

        ;;

    esac
  done

  if [[ -z ${args['name']+x} ]]; then
    printf "missing required argument: NAME\nusage: secrets new NAME [OPTIONS] [--] [ARBITRARY OPTIONS TO USE AS KEY/VALUE DATA FOR YOUR SECRET FILE....]\n" >&2

    exit 1
  fi

  filter_error=$(filter_ensure_default_files)
  if [[ -n $filter_error ]]; then
    echo "$filter_error" >&2
    exit 1
  fi

}

secrets_get_parse_requirements() {

  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --help | -h)
        long_usage=yes
        secrets_get_usage
        exit
        ;;

      *)
        break
        ;;

    esac
  done

  missing_deps=

  if ! command -v yq >/dev/null 2>&1; then
    printf "missing dependency: yq\n" >&2
    missing_deps=1
  else
    deps['yq']="$(command -v yq | head -n1)"
  fi

  if ! command -v sha1sum >/dev/null 2>&1; then
    printf "missing dependency: sha1sum\n" >&2
    missing_deps=1
  else
    deps['sha1sum']="$(command -v sha1sum | head -n1)"
  fi

  if [[ -n $missing_deps ]]; then
    exit 1
  fi

  action="get"

  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in

      --key)

        if [[ -n ${2+x} ]]; then
          args['--key']="$2"
          shift
          shift
        else
          printf "%s\n" "--key requires an argument: --key YAML-KEY" >&2
          exit 1
        fi
        ;;

      --namespace)

        if [[ -n ${2+x} ]]; then
          args['--namespace']="$2"
          shift
          shift
        else
          printf "%s\n" "--namespace requires an argument: --namespace NAMESPACE" >&2
          exit 1
        fi
        ;;

      --passphrase)

        if [[ -n ${2+x} ]]; then
          args['--passphrase']="$2"
          shift
          shift
        else
          printf "%s\n" "--passphrase requires an argument: --passphrase PASSPHRASE" >&2
          exit 1
        fi
        ;;

      -?*)
        printf "invalid option: %s\n" "$key" >&2
        exit 1
        ;;

      *)

        if [[ -z ${args['name']+x} ]]; then
          args['name']=$1
          shift
        else
          printf "invalid argument: %s\n" "$key" >&2
          exit 1
        fi

        ;;

    esac
  done

  if [[ -z ${args['name']+x} ]]; then
    printf "missing required argument: NAME\nusage: secrets get NAME [OPTIONS]\n" >&2

    exit 1
  fi

}

secrets_edit_parse_requirements() {

  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --help | -h)
        long_usage=yes
        secrets_edit_usage
        exit
        ;;

      *)
        break
        ;;

    esac
  done

  missing_deps=

  if ! command -v yq >/dev/null 2>&1; then
    printf "missing dependency: yq\n" >&2
    missing_deps=1
  else
    deps['yq']="$(command -v yq | head -n1)"
  fi

  if ! command -v sha1sum >/dev/null 2>&1; then
    printf "missing dependency: sha1sum\n" >&2
    missing_deps=1
  else
    deps['sha1sum']="$(command -v sha1sum | head -n1)"
  fi

  if [[ -n $missing_deps ]]; then
    exit 1
  fi

  action="edit"

  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in

      --preview)

        args['--preview']=1
        shift
        ;;

      --from-yaml)

        if [[ -n ${2+x} ]]; then
          args['--from-yaml']="$2"
          shift
          shift
        else
          printf "%s\n" "--from-yaml requires an argument: --from-yaml FILE-OR-STRING" >&2
          exit 1
        fi
        ;;

      --namespace)

        if [[ -n ${2+x} ]]; then
          args['--namespace']="$2"
          shift
          shift
        else
          printf "%s\n" "--namespace requires an argument: --namespace NAMESPACE" >&2
          exit 1
        fi
        ;;

      --passphrase)

        if [[ -n ${2+x} ]]; then
          args['--passphrase']="$2"
          shift
          shift
        else
          printf "%s\n" "--passphrase requires an argument: --passphrase PASSPHRASE" >&2
          exit 1
        fi
        ;;

      --)
        shift
        other_args+=("$@")
        break
        ;;

      -?*)
        other_args+=("$1")
        shift
        ;;

      *)

        if [[ -z ${args['name']+x} ]]; then
          args['name']=$1
          shift
        else
          other_args+=("$1")
          shift
        fi

        ;;

    esac
  done

  if [[ -z ${args['name']+x} ]]; then
    printf "missing required argument: NAME\nusage: secrets edit NAME [OPTIONS] [--] [ARBITRARY OPTIONS TO USE AS KEY/VALUE DATA FOR YOUR SECRET FILE....]\n" >&2

    exit 1
  fi

}

initialize() {
  declare -g version=""
  set -e

  SECRETS_CLI_VERSION="v0.1.0"
  SECRETS_CLI_PATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
  version=$SECRETS_CLI_VERSION

}

run() {

  declare -g long_usage=''
  declare -g -A args=()
  declare -g -a other_args=()
  declare -g -A deps=()
  declare -g -a env_var_names=()
  declare -g -a input=()

  normalize_input "$@"
  parse_requirements "${input[@]}"

  case "$action" in
    "ls") secrets_ls_command ;;
    "rm") secrets_rm_command ;;
    "new") secrets_new_command ;;
    "get") secrets_get_command ;;
    "edit") secrets_edit_command ;;
  esac
}

initialize
run "$@"
